version: "3.3"

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        networks:
            - main
        ports:
            - 80:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../source:/project/source/

    php:
        image: chialab/php-dev:8.2-fpm
        restart: unless-stopped
        working_dir: /project/source
        networks:
            - main
        ports:
            - 9000:9000
        volumes:
            - ../source:/project/source/

networks:
    main:
